### ISSUE TITLE
Schema 

### ISSUE THREAD

**Issue by PLUCS2** [juliajykim/Zip#2]
- [x] I do not see a User location on zillow? Name seems optional (good on making null an acceptable option for name on the user table) - confirming that users will not be landlords for MVP 1 (for BONUS Users can be land lords and post their own listings) 
- [x] What is `type` on the Properties table? (you may want to have a types table where properties hold a foreign_id referencing the type if it is used in searching (this just makes searching easier as you can use an association rather than a sql query) 
- [x] You may want to have a "amenities table" - for things like Parking, Heating, Cooling, etc. with a joins table to connect it with properties (rather than having a number of boolean columns) - this will help with searching 
- [x] I do not see Reviews on Zillow - are they there? 

This looks really excellent! Nice work and let me know if you have any question

**Comment by juliajykim** [comment]
> * [ ]  I do not see a User location on zillow? Name seems optional (good on making null an acceptable option for name on the user table) - confirming that users will not be landlords for MVP 1 (for BONUS Users can be land lords and post their own listings)

* I put location(optional) for sellers(agents in Zillow app) because you can search agents by their name or location. 
If dividing users into two group (regular property hunter / seller) is a bonus feature, then will posting/editing properties also be bonus?
  
  <p>&nbsp;</p>

> * [ ]  What is `type` on the Properties table? (you may want to have a types table where properties hold a foreign_id referencing the type if it is used in searching (this just makes searching easier as you can use an association rather than a sql query)

*  Type was either house, condos, apartments, or townhomes. I will separate them into another table as you advised.
  
  <p>&nbsp;</p>

> * [ ]  You may want to have a "amenities table" - for things like Parking, Heating, Cooling, etc. with a joins table to connect it with properties (rather than having a number of boolean columns) - this will help with searching

*  That was actually what I was unsure about.
 I was debating between tracking amenities in the Properties table or separating them as an independent table. It totally makes sense separating them in searching purposes!
  
  <p>&nbsp;</p>

> * [ ]  I do not see Reviews on Zillow - are they there?

*  Review was under the Find Agent tap -> individual agent profile page.
If dividing users into 2 types is a bonus, I will move the review part to the bonus as well. 

**Thank you so much!**
